### PR TITLE
fix: Add world height accommodation, fix texture tracking and world ticking

### PR DESCRIPTION
**Pull request by FlashyReese**
Please squash :>

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
> Please squash :>

This includes a lot of commits from sodium upstream, so squashing will mean that this will forever be commits behind. The better option is to either merge upstream sodium, or rebase onto upstream sodium, and *then* squashing this PR, which will both update this fork to upstream *and* cleanup the rest of the commits in this PR.

**Comment by Kroppeb** [comment]
> Please squash :>

this contains commits from next that aren't in thingl. I don't think I should squash this.

**Comment by DragonEggBedrockBreaking** [comment]
> this contains commits from next that aren't in thingl. I don't think I should squash this.

See my comment above

**Comment by DragonEggBedrockBreaking** [comment]
resolve conflicts smh

**Comment by FlashyReese** [comment]
Superseded by #3

**Pull request closed without merging**
